#!/bin/sh

super='Mod4'
alt='Mod4'
ctrl='Mod4'
sft='Mod4'
caps='Mod4'

run_menu='fuzzel --width 30 --log-level=none'
playerctl_script="luajit $HOME/.config/scripts/playerctl.lua"
wallpaper_script="luajit $HOME/.config/wallpapers/wallpaper.lua "


# Autostart
riverctl spawn 'wlr-randr --output HDMI-A-1 --mode 2560x1440@143.912003Hz'
riverctl spawn 'swww init > /dev/null 2>&1'
riverctl spawn "$wallpaper_script inc 0 0 > /dev/null 2>&1"
riverctl spawn 'gammastep -r > /dev/null 2>&1'
riverctl spawn '$HOME/.config/dwl/someblocks/someblocks -m 1 | awk "{print \"all \" \$0; fflush();}" | $HOME/.config/river/sandbar/sandbar -hide-vacant-tags -font "Sans:size=14" -tags 14 T q w n d s a z t f c g v h'
riverctl spawn 'pulseaudio --start > /dev/null 2>&1'
riverctl spawn 'wl-paste --watch cliphist store > /dev/null 2>&1'
riverctl spawn 'amixer set Capture nocap > /dev/null 2>&1'
riverctl spawn 'fnott > /dev/null 2>&1'
riverctl spawn 'pgrep keepassxc > /dev/null || keepassxc > /dev/null 2>&1'
riverctl spawn 'pgrep tutanota > /dev/null || tutanota-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland > /dev/null 2>&1'
riverctl spawn 'blueman-applet > /dev/null 2>&1'
#riverctl spawn wlr-randr --output DP-1 --off

tag() {
    index=$1
    key=$2
    name=$3

    tags=$((1 << (index - 1)))
    riverctl map normal Alt               $key set-focused-tags     $tags
    riverctl map normal Alt+Shift         $key set-view-tags        $tags
    riverctl map normal Alt+Control       $key toggle-focused-tags  $tags
    riverctl map normal Alt+Shift+Control $key toggle-view-tags     $tags
    echo "$tags"
}
_tag="$(tag 1  'Tab' 'T')"
_tag="$(tag 2  'Q' 'q')"
_tag="$(tag 3  'W' 'w')"
_tag="$(tag 4  'N' 'n')"
_tag="$(tag 5  'D' 'd')"
_tag="$(tag 6  'S' 's')"
_tag="$(tag 7  'A' 'a')"
_tag="$(tag 8  'Z' 'z')"
_tag="$(tag 9  'T' 't')"
_tag="$(tag 10 'F' 'f')"
_tag="$(tag 11 'C' 'c')"
_tag="$(tag 12 'G' 'g')"
_tag="$(tag 13 'V' 'v')"
_tag="$(tag 14 'H' 'h')"

riverctl declare-mode passthrough
# Spawn
riverctl map normal             Alt                 Return  spawn "alacritty"
riverctl map normal             Alt                 R       spawn "$run_menu"

# Power options
for mode in normal locked; do
    riverctl map $mode          Super+Shift+Control Q       exit
    riverctl map $mode          Super+Shift+Control P       spawn 'loginctl poweroff'
    riverctl map $mode          Super+Shift+Control R       spawn 'loginctl reboot'
    riverctl map $mode          Super+Shift+Control S       spawn 'playerctl pause -a; loginctl suspend; swaylock'
    riverctl map $mode          Super+Shift+Control H       spawn 'loginctl hibernate'
done
riverctl map normal             Super+Shift+Control M       spawn 'touch /tmp/restart_river; riverctl exit'
riverctl map normal             Super+Shift+Control L       spawn 'playerctl pause -a; swaylock'

# Client manipulation
riverctl map normal             Super+Shift         C       close
riverctl map normal             Super+Shift         Space   toogle-float
riverctl map normal             Super               F       toogle-fullscreen

riverctl map -repeat normal     Super+Control       Y       move left 10
riverctl map -repeat normal     Super+Control       U       move down 10
riverctl map -repeat normal     Super+Control       I       move up 10
riverctl map -repeat normal     Super+Control       O       move right 10

riverctl map -repeat normal     Super+Control       H       resize horizontal -10
riverctl map -repeat normal     Super+Control       J       resize vertical 10
riverctl map -repeat normal     Super+Control       K       resize vertical -10
riverctl map -repeat normal     Super+Control       L       resize horizontal 10

# Focus manipulation
riverctl map normal             Super+Control       Return  zoom
riverctl map normal             Super               J       focus-view next
riverctl map normal             Super               K       focus-view previous
riverctl map normal             Super+Shift         J       swap next
riverctl map normal             Super+Shift         K       swap previous

# Layout manipulation
riverctl map normal             Super               H       send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal             Super               L       send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal             Super+Shift         H       send-layout-cmd rivertile "main-count +1"
riverctl map normal             Super+Shift         L       send-layout-cmd rivertile "main-count -1"

# Playerctl
map_playerctl() {
    for mode in normal locked passthrough; do
        riverctl map $mode      Mod3                $1      spawn "$playerctl_script \"$2\" 1"
        riverctl map $mode      Mod3+Shift          $1      spawn "$playerctl_script \"$2\" 2"
    done
}

map_playerctl 'Tab' 'play-pause'
map_playerctl 'Q'   'next'
map_playerctl 'A'   'previous'
map_playerctl 'W'   'volume 0.02%+'
map_playerctl 'S'   'volume 0.02%-'
for mode in normal locked passthrough; do
    riverctl map $mode          Mod3+Control        Tab     spawn "$playerctl_script swap -1"
    riverctl map $mode          None                XF86AudioPlay spawn "playerctl play-pause"
done

map normal                      Mod3+Control        Q       spawn "pacmd set-default-sink \"\$(pactl list sinks short | awk '{print \$1 \" <> \" substr(\$2,13) }' | tr '-' ' ' | tr '_' ' ' | fuzzel -d --log-level=none --width 50 | awk '{print \$1}')\""

# Misc caps keys
riverctl map normal             Mod3                1       spawn 'cliphist list | fuzzel --width 100 -d --log-level=none | cliphist decode | wl-copy'
riverctl map normal             Mod3+Control        1       spawn "rm $HOME/.cache/cliphist/db" 
riverctl map normal             Mod3                3       spawn '$HOME/.config/dotfiles/scripts/wayland/togglemonitors.sh'
riverctl map normal             Mod3                4       spawn '$HOME/.config/dotfiles/scripts/wayland/change-res.sh'

riverctl map normal             Mod3                T       spawn "$wallpaper_script wayland-gui"
riverctl map normal             Mod3                Z       spawn 'grim - | wl-copy'
riverctl map normal             Mod3                C       spawn 'grim -g "$(slurp)" - | wl-copy'

# Passthrough mode
riverctl map normal             Super               F11     enter-mode passthrough
riverctl map passthrough        Super               F11     enter-mode normal

# Mouse buttons
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75
riverctl border-width 0

#riverctl rule-add float -app-id 'float*' -title 'foo'

riverctl focus-follows-cursor disabled
riverctl hide-cursor 2000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme 'breeze_cursors' 24
riverctl attach-mode bottom
riverctl set-repeat 50 200

# Map Caps to a modkey Mod3
riverctl keyboard-layout -options 'caps:shiftlock' 'pl,us'

riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-count 1 -main-ratio 0.5 -main-location left &

